local fixture_runner = require("fixture_runner")

return function(runner, helper)
  fixture_runner.register(runner, helper, require("fixtures.basic_layout"))
  fixture_runner.register(runner, helper, require("fixtures.justify_content"))
  fixture_runner.register(runner, helper, require("fixtures.align_items"))
  fixture_runner.register(runner, helper, require("fixtures.align_self"))
  fixture_runner.register(runner, helper, require("fixtures.yoga_justify_content"))
  fixture_runner.register(runner, helper, require("fixtures.yoga_align_items"))
  fixture_runner.register(runner, helper, require("fixtures.yoga_align_self"))
  fixture_runner.register(runner, helper, require("fixtures.percentage_dimensions"))
  fixture_runner.register(runner, helper, require("fixtures.percentage_spacing"))
  fixture_runner.register(runner, helper, require("fixtures.yoga_percentage"))
  fixture_runner.register(runner, helper, require("fixtures.yoga_minmax_dimension"))
  fixture_runner.register(runner, helper, require("fixtures.yoga_display"))
end
