return function(runner)
  runner:test("love2d example syntax", function()
    assert(loadfile("examples/love2d/conf.lua"))
    assert(loadfile("examples/love2d/main.lua"))
    assert(loadfile("examples/love2d/layouts/menu.lua"))
    assert(loadfile("examples/love2d/layouts/inventory.lua"))
    assert(loadfile("examples/love2d/layouts/settings.lua"))
    assert(loadfile("examples/love2d/layouts/flex_spacing.lua"))
    assert(loadfile("examples/love2d/layouts/axis_gap.lua"))
    assert(loadfile("examples/love2d/layouts/flex_basis.lua"))
    assert(loadfile("examples/love2d/layouts/flex_shrink.lua"))
    assert(loadfile("examples/love2d/layouts/flex_wrap.lua"))
    assert(loadfile("examples/love2d/layouts/align_content.lua"))
    assert(loadfile("examples/love2d/layouts/aspect_ratio.lua"))
    assert(loadfile("examples/love2d/layouts/justify.lua"))
    assert(loadfile("examples/love2d/layouts/align.lua"))
    assert(loadfile("examples/love2d/layouts/percent.lua"))
    assert(loadfile("examples/love2d/layouts/measure.lua"))
    assert(loadfile("examples/love2d/layouts/minmax.lua"))
    assert(loadfile("examples/love2d/layouts/display.lua"))
    assert(loadfile("examples/love2d/layouts/absolute.lua"))
    assert(loadfile("examples/love2d/layouts/relative.lua"))
    assert(loadfile("examples/love2d/layouts/overlay.lua"))
  end)
end
