package.path = "src/?.lua;src/?/init.lua;tests/?.lua;" .. package.path

local helper = require("helper")
local runner = helper.new_runner()

require("core_test")(runner, helper)
require("ui_test")(runner, helper)
require("runtime_test")(runner, helper)
require("flip_test")(runner, helper)
require("measure_test")(runner, helper)
require("measure_mode_test")(runner, helper)
require("yoga_measure_test")(runner, helper)
require("minmax_test")(runner, helper)
require("percentage_test")(runner, helper)
require("auto_size_test")(runner, helper)
require("flex_basis_test")(runner, helper)
require("flex_basis_fit_content_test")(runner, helper)
require("size_overflow_test")(runner, helper)
require("flex_shrink_test")(runner, helper)
require("gap_test")(runner, helper)
require("aspect_ratio_test")(runner, helper)
require("flex_wrap_test")(runner, helper)
require("display_test")(runner, helper)
require("absolute_test")(runner, helper)
require("relative_test")(runner, helper)
require("rounding_test")(runner, helper)
require("dirty_test")(runner, helper)
require("layout_cache_test")(runner, helper)
require("measure_cache_test")(runner, helper)
require("had_overflow_test")(runner, helper)
require("overflow_test")(runner, helper)
require("love2d_test")(runner, helper)
require("fixture_test")(runner, helper)

runner:run()
